name: Build and Upload JAR to Release

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read  # 允许读取仓库内容
      packages: write  # 允许写入包
      id-token: write  # 允许获取身份令牌（这对于 GitHub API 访问权限有帮助）
      actions: write  # 允许写入 actions
      issues: write  # 可选：如果需要更高权限来操作 release 资源

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install

    - name: Get version from pom.xml
      id: get_version
      run: |
        # 使用 Maven 解析 pom.xml 中的版本号
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Version found: $VERSION"

    - name: Create Release Draft via GitHub API
      run: |
        curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{
                "tag_name": "${{ env.VERSION }}",
                "target_commitish": "main",
                "name": "${{ env.VERSION }}",
                "body": "Release ${ { env.VERSION }}",
                "draft": true,
                "prerelease": false
              }' \
          https://api.github.com/repos/${{ github.repository }}/releases

    - name: Upload JAR to Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/PremiumTerminal-*.jar  # 上传构建好的 JAR 文件
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GITHUB_TOKEN 进行 API 操作
