name: Build and Upload JAR to Release

on:
  push: # 在push时触发
    tags: # 标签  这里标识在push tag时触发
      - 'v*' # 以v开头的版本

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read  # 允许读取仓库内容
      packages: write  # 允许写入包
      id-token: write  # 允许获取身份令牌（这对于 GitHub API 访问权限有帮助）
      actions: write  # 允许写入 actions
      issues: write  # 可选：如果需要更高权限来操作 release 资源

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install

    - name: Upload # 上传
      uses: softprops/action-gh-release@v2 # 使用第三方actions 上传
      if: startsWith(github.ref, 'refs/tags/') # 仅在tag时上传
      with:
        files: target/PremiumTerminal-*.jar  # 上传构建好的 JAR 文件
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}  # 使用 GITHUB_TOKEN 进行 API 操作
